### ISSUE TITLE
'Request contains an invalid argument.'

### ISSUE THREAD

**Issue by quexx2** [yusufusta/ytstudio#3]
When trying to upload a video I'm getting this error:
`{'error': {'code': 400, 'message': 'Request contains an invalid argument.', 'errors': [{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}], 'status': 'INVALID_ARGUMENT'}}`
After a bit of investigation I've determined that this is happening because no sessionToken is being provided wben uploading the video.

**Comment by yusufusta** [comment]
Fixed with latest commit
