### ISSUE TITLE
Help Please!

### ISSUE THREAD

**Issue by Lemonsflo** [yusufusta/ytstudio#5]
I'm new to this topic) Can you help me?
I downloaded the files using pip, what should I do next?
![sfsre](https://user-images.githubusercontent.com/94681971/143576738-ab7d1d50-7459-4c8f-98e1-0ae58ccdc4e9.PNG)

**Comment by yusufusta** [comment]
What you want?

Please look at the [README](https://github.com/yusufusta/ytstudio#features) if you want examples

**Comment by Lemonsflo** [comment]
I don't understand anything about it at all ( And the program is very necessary. I don't understand how to use all these and assemble them at all...

**Comment by yusufusta** [comment]
Okey you should learn Python language. This is a library not a program.
