### ISSUE TITLE
Translating Delete to NodeJS?

### ISSUE THREAD

**Issue by bostonnico** [yusufusta/ytstudio#8]
Hey man, thanks for this initial translation of this great API tool !!!

Do you perhaps know of a tool that can translate your Delete function over to NodeJS (since adasq's scripts don't have it yet) ?
I'm allergic to using Python, unfortunately, and wouldn't be able to get it running on my machines. I've done thorough searches online but can't find any tools for doing a proper translation for this particular kind of script.

Cheers!

**Comment by yusufusta** [comment]
sorry i don't have any authority in that library.
